name: Validate Catalog JSON

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validate docs/medications_catalog.json against schema
        run: npx --yes ajv-cli@5.0.0 validate -s schema/catalog.schema.json -d docs/medications_catalog.json --strict=true

      # Optional: show a summary of entry count (simple sanity check)
      - name: Count entries
        run: |
          node -e "const fs=require('fs');const d=JSON.parse(fs.readFileSync('docs/medications_catalog.json','utf8'));console.log('Entries:', Array.isArray(d)?d.length:'N/A'); if(!Array.isArray(d)||d.length<100){console.warn('Warning: entry count seems low');}"
